#!/usr/bin/fish

pnpm run i
pnpm run protobuild
pnpm run build
sudo rm -rf /opt/taskable-frontend
sudo mkdir /opt/taskable-frontend
sudo chown ubuntu:ubuntu /opt/taskable-frontend
sudo cp .output/* /opt/taskable-frontend

# update service
sudo systemctl restart taskable-frontend